import { Component, type ComponentType, type ErrorInfo, type ReactNode } from 'react'
import { Skeleton } from '@/components/ui/skeleton'

/**
 * RegionErrorBoundary (SYSTEM-MANAGED) — isolates each auto-mounted region.
 * Regions all render together, so without this a runtime crash in ONE region
 * would blank the ENTIRE app and the failure would be mis-attributed to
 * whichever region rendered first. This contains the crash to its own region
 * (the rest of the app stays usable) and logs it with the region name so the
 * real culprit is identifiable in the console.
 */
class RegionErrorBoundary extends Component<
  { region: string; children: ReactNode },
  { error: Error | null }
> {
  state = { error: null as Error | null }

  static getDerivedStateFromError(error: Error) {
    return { error }
  }

  componentDidCatch(error: Error, info: ErrorInfo) {
    // Surface the culprit region + component stack for the validator/agent.
    console.error(
      `[region:${this.props.region}] crashed and was isolated:`,
      error,
      info.componentStack,
    )
  }

  render() {
    if (this.state.error) {
      return (
        <section
          role="alert"
          data-region-error={this.props.region}
          className="rounded-lg border border-destructive/40 bg-destructive/5 p-4 text-sm text-destructive"
        >
          This section (<code>{this.props.region}</code>) failed to load.
          {this.state.error.message ? ` (${this.state.error.message})` : null}
        </section>
      )
    }
    return this.props.children
  }
}

/**
 * MainView — the app shell (SYSTEM-MANAGED — do NOT edit this file).
 *
 * Regions AUTO-MOUNT. Every file in `components/regions/*.tsx` is
 * discovered and rendered here automatically, ordered by filename — you
 * NEVER import or wire a component into MainView by hand. To add a screen
 * region, just create `components/regions/NN_slug.tsx` with a default
 * export; it appears on screen. To change one, edit that file in place.
 *
 * Wireframe phase: the region files start as Skeleton stubs; each feature
 * build replaces its region file with the real component. When no region
 * files exist yet, the placeholder below shows (the untouched-scaffold
 * sentinel the platform's gates key on).
 */

// Vite eager glob: import every region module at build time. `eager`
// means the default exports are available synchronously (no lazy/suspense).
const regionModules = import.meta.glob<{ default: ComponentType }>(
  './regions/*.tsx',
  { eager: true },
)

// Deterministic order = filename (regions are named NN_slug.tsx).
const regions = Object.keys(regionModules)
  .sort()
  .map((path) => ({
    key: path.replace(/^.*\/(.*)\.tsx$/, '$1'),
    RegionComponent: regionModules[path].default,
  }))
  .filter((r) => typeof r.RegionComponent === 'function')

export function MainView() {
  // No region files yet = the untouched scaffold (the platform's gates key
  // on the ABSENCE of components/regions/*.tsx, not on this file). Shows a
  // placeholder until the first region is written.
  if (regions.length === 0) {
    return (
      <main className="min-h-screen p-6">
        <div className="mx-auto flex max-w-6xl flex-col gap-8">
          <section className="flex flex-col gap-4">
            <Skeleton className="h-8 w-64" />
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {Array.from({ length: 6 }).map((_, i) => (
                <Skeleton key={i} className="h-40" />
              ))}
            </div>
          </section>
        </div>
      </main>
    )
  }

  return (
    <main className="min-h-screen p-6">
      <div className="mx-auto flex max-w-6xl flex-col gap-8">
        {regions.map(({ key, RegionComponent }) => (
          <RegionErrorBoundary key={key} region={key}>
            <RegionComponent />
          </RegionErrorBoundary>
        ))}
      </div>
    </main>
  )
}
