/**
 * GENERATED from config/schema.json — DO NOT EDIT.
 *
 * One interface per declared PocketBase collection, field names exactly
 * as declared (plus PB system fields id/created/updated). Regenerated by
 * the platform on every schema write.
 *
 * Import from here:  import type { Card } from '../types.gen'
 * App-specific NON-entity types still go in types.ts.
 */

// No collections declared yet — define them in config/schema.json.
export {}
