"""
Platform-owned schema migration for Living UI projects.

Additive column migration used to live only in the template's database.py,
which meant old projects never got it: an agent adding a column to models.py
would restart into HTTP 500s ("no such column") and a blocked smoke test.
This module makes migration a PLATFORM step — the manager runs it before
every backend start, and the livingui CLI exposes it as `migrate` — so every
native project gets it regardless of when it was created.

It works by executing a standalone script (written to the project's logs
dir) inside the project's backend directory with the same interpreter the
backend runs under: the script imports the project's own models.py, runs
Base.metadata.create_all (new tables), ALTER TABLE ADD COLUMN for any
model column missing on disk, and RECONCILES stale columns: a column on
disk that is no longer in the model (field removed or renamed in
schema.json) is removed by rebuilding the table from the model and copying
the shared columns' data. Without this, a stale NOT NULL column makes
every INSERT fail with an opaque 500 that costs agents whole debug cycles.

Also provides a cheap, import-free drift detector (regex over models.py)
used by the CLI to warn in --help output and to make unknown-column errors
prescriptive.
"""

import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List

try:
    from loguru import logger
except ImportError:
    import logging

    logger = logging.getLogger(__name__)

# Standalone migration script. Runs with cwd=<project>/backend so that
# `import models` resolves the project's own modules, exactly like uvicorn.
MIGRATION_SCRIPT = '''\
"""Auto-generated by CraftBot — schema reconcile migration. Safe to delete."""
import os
import sys

# Run with cwd=<project>/backend, but sys.path[0] is this script's own dir
# (logs/) — put the cwd first so `import models` resolves the project's code.
sys.path.insert(0, os.getcwd())


def database_url():
    """Mirror of database.py's resolution: backend/.env DATABASE_URL, else
    the local SQLite file. cwd is <project>/backend."""
    try:
        with open(".env", "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, value = line.partition("=")
                if key.strip() == "DATABASE_URL":
                    url = value.strip().strip("'\\"")
                    if url and not url.startswith("sqlite"):
                        return url
    except OSError:
        pass
    return "sqlite:///living_ui.db"


def main():
    try:
        from sqlalchemy import create_engine, inspect, text
        from models import Base
    except Exception as e:
        print(f"MIGRATE SKIP: could not import models ({e})")
        return 0

    url = database_url()
    if url.startswith("sqlite"):
        engine = create_engine(url, connect_args={"check_same_thread": False})
    else:
        engine = create_engine(url, pool_pre_ping=True)
    Base.metadata.create_all(bind=engine)

    inspector = inspect(engine)
    existing_tables = set(inspector.get_table_names())
    added = []
    rebuilt = []
    with engine.begin() as conn:
        for table in Base.metadata.sorted_tables:
            if table.name not in existing_tables:
                continue
            disk_cols = {c["name"] for c in inspector.get_columns(table.name)}
            model_cols = [c.name for c in table.columns]
            stale = sorted(disk_cols - set(model_cols))

            if stale:
                # A column on disk that the model no longer declares (field
                # removed or renamed). A stale NOT NULL column breaks every
                # INSERT, so rebuild the table from the model and copy the
                # shared columns' data across.
                shared = [c for c in model_cols if c in disk_cols]
                tmp = table.name + "__craftbot_stale"
                try:
                    conn.execute(text(
                        f'ALTER TABLE "{table.name}" RENAME TO "{tmp}"'
                    ))
                    table.create(bind=conn)
                    if shared:
                        # New columns get their scalar defaults explicitly:
                        # model defaults are Python-side (no DDL DEFAULT),
                        # so a plain INSERT..SELECT would NULL-violate new
                        # required columns (e.g. a renamed enum field).
                        fill_cols, fill_params = [], {}
                        for column in table.columns:
                            if column.name in shared:
                                continue
                            default = column.default
                            if default is not None and getattr(
                                default, "is_scalar", False
                            ):
                                if isinstance(default.arg, (str, int, float, bool)):
                                    fill_cols.append(column.name)
                                    fill_params["d_" + column.name] = default.arg
                        cols_sql = ", ".join(
                            '"' + c + '"' for c in shared + fill_cols
                        )
                        select_sql = ", ".join(
                            ['"' + c + '"' for c in shared]
                            + [":d_" + c for c in fill_cols]
                        )
                        try:
                            conn.execute(text(
                                f'INSERT INTO "{table.name}" ({cols_sql}) '
                                f'SELECT {select_sql} FROM "{tmp}"'
                            ), fill_params)
                        except Exception as e:
                            print(
                                f"MIGRATE WARN: {table.name} rebuilt but rows "
                                f"not copied ({e}) — table starts empty"
                            )
                    conn.execute(text(f'DROP TABLE "{tmp}"'))
                    rebuilt.append(
                        f"{table.name} (removed stale: {', '.join(stale)})"
                    )
                except Exception as e:
                    print(f"MIGRATE WARN: could not rebuild {table.name}: {e}")
                continue

            for column in table.columns:
                if column.name in disk_cols:
                    continue
                col_type = column.type.compile(engine.dialect)
                ddl = (
                    f'ALTER TABLE "{table.name}" ADD COLUMN '
                    f'"{column.name}" {col_type}'
                )
                if column.default is not None and getattr(
                    column.default, "is_scalar", False
                ):
                    ddl += f" DEFAULT {column.default.arg!r}"
                try:
                    conn.execute(text(ddl))
                    added.append(f"{table.name}.{column.name}")
                except Exception as e:
                    print(f"MIGRATE WARN: could not add {table.name}.{column.name}: {e}")
    if added:
        print("MIGRATE ADDED: " + ", ".join(added))
    if rebuilt:
        print("MIGRATE REBUILT: " + "; ".join(rebuilt))
    if not added and not rebuilt:
        print("MIGRATE OK: schema up to date")
    return 0

if __name__ == "__main__":
    sys.exit(main())
'''


def external_database_url(project_path: Path) -> str:
    """The project's external DATABASE_URL from backend/.env, or "" when it
    runs on the default local SQLite. Mirrors the template database.py."""
    env_file = Path(project_path) / "backend" / ".env"
    try:
        if env_file.exists():
            for line in env_file.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, value = line.partition("=")
                if key.strip() == "DATABASE_URL":
                    url = value.strip().strip("'\"")
                    if url and not url.startswith("sqlite"):
                        return url
    except OSError:
        pass
    return ""


def run_migration(
    project_path: Path, python_executable: str = "", timeout: float = 60.0
) -> Dict[str, Any]:
    """Run the additive migration for a native project. Best-effort.

    Returns {"status": "ok"|"skipped"|"error", "output": str, "added": [...]}.
    Never raises — a migration failure should surface, not block.
    """
    backend = Path(project_path) / "backend"
    if not (backend / "models.py").exists():
        return {"status": "skipped", "output": "no backend/models.py", "added": [], "rebuilt": []}
    if not external_database_url(project_path) and not (backend / "living_ui.db").exists():
        # First launch on local SQLite: the app's own create_all builds the
        # fresh schema. (With an external DATABASE_URL we always run — the
        # remote schema may exist and need reconciling.)
        return {"status": "skipped", "output": "no database yet", "added": [], "rebuilt": []}

    logs_dir = backend / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)
    script_path = logs_dir / "_craftbot_migrate.py"
    try:
        script_path.write_text(MIGRATION_SCRIPT, encoding="utf-8")
    except Exception as e:
        return {"status": "error", "output": f"could not write script: {e}", "added": [], "rebuilt": []}

    python = python_executable or sys.executable
    creation_flags = getattr(subprocess, "CREATE_NO_WINDOW", 0)
    try:
        completed = subprocess.run(
            [python, str(script_path)],
            cwd=str(backend),
            capture_output=True,
            text=True,
            timeout=timeout,
            creationflags=creation_flags,
        )
    except subprocess.TimeoutExpired:
        return {"status": "error", "output": f"migration timed out after {timeout}s", "added": [], "rebuilt": []}
    except Exception as e:
        return {"status": "error", "output": str(e), "added": [], "rebuilt": []}

    output = ((completed.stdout or "") + (completed.stderr or "")).strip()
    added: List[str] = []
    rebuilt: List[str] = []
    for line in output.splitlines():
        if line.startswith("MIGRATE ADDED: "):
            added = [c.strip() for c in line[len("MIGRATE ADDED: "):].split(",")]
        elif line.startswith("MIGRATE REBUILT: "):
            rebuilt = [c.strip() for c in line[len("MIGRATE REBUILT: "):].split(";")]
    if completed.returncode != 0:
        logger.warning(f"[LIVING_UI:MIGRATE] {project_path}: {output[-500:]}")
        return {
            "status": "error",
            "output": output[-1000:],
            "added": added,
            "rebuilt": rebuilt,
        }
    if added or rebuilt:
        logger.info(
            f"[LIVING_UI:MIGRATE] {project_path}: added {added}, rebuilt {rebuilt}"
        )
    return {
        "status": "ok",
        "output": output[-1000:],
        "added": added,
        "rebuilt": rebuilt,
    }


# ---------------------------------------------------------------------------
# Import-free drift detection (heuristic, for help text and error messages)
# ---------------------------------------------------------------------------

_TABLENAME_RE = re.compile(r"__tablename__\s*=\s*[\"']([A-Za-z_][A-Za-z0-9_]*)[\"']")
_COLUMN_RE = re.compile(r"^\s+([a-z_][a-z0-9_]*)\s*(?::[^=]+)?=\s*(?:Column|mapped_column)\(", re.M)


def declared_schema(project_path: Path) -> Dict[str, List[str]]:
    """Parse models.py (regex, no import) → {table_name: [column names]}.

    Heuristic but reliable for template-style models (one class per
    __tablename__, `name = Column(...)` attributes). Used only for warnings
    and error enrichment — never for actual migration decisions.
    """
    models = Path(project_path) / "backend" / "models.py"
    if not models.exists():
        return {}
    try:
        source = models.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return {}

    tables: Dict[str, List[str]] = {}
    # Split by class blocks: find each __tablename__ and collect Column
    # attributes until the next class definition.
    class_blocks = re.split(r"\nclass\s+", source)
    for block in class_blocks:
        table_match = _TABLENAME_RE.search(block)
        if not table_match:
            continue
        columns = _COLUMN_RE.findall(block)
        if columns:
            tables[table_match.group(1)] = columns
    return tables


def detect_drift(
    project_path: Path, db_schema: Dict[str, Any]
) -> Dict[str, List[str]]:
    """Compare models.py declarations against the live DB schema.

    Returns {"missing_tables": [...], "missing_columns": ["table.col", ...]}.
    Empty lists mean no detected drift.
    """
    declared = declared_schema(Path(project_path))
    missing_tables: List[str] = []
    missing_columns: List[str] = []
    for table, columns in declared.items():
        if table not in db_schema:
            missing_tables.append(table)
            continue
        db_columns = set(db_schema[table].get("columns", {}).keys())
        for column in columns:
            if column not in db_columns:
                missing_columns.append(f"{table}.{column}")
    return {"missing_tables": missing_tables, "missing_columns": missing_columns}
