"""TypeScript generation from config/schema.json (PocketBase collections).

The backend is PocketBase — collections declared in PB's native
import format. On every schema write the platform regenerates:

- frontend/types.gen.ts — one interface per collection (field names
  exactly as declared + PB system fields id/created/updated);
- frontend/api.gen.ts — typed helpers over the PB SDK
  (api.<name>.getFullList/getList/getOne/create/update/delete +
  use<Name>() hooks wrapping useEntities).

Deterministic, no LLM involved, fail-silent (generation must never break
a build; schema errors surface loudly at the collections-import step).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

try:
    from loguru import logger
except ImportError:
    import logging

    logger = logging.getLogger(__name__)

_TS_TYPES = {
    "text": "string",
    "editor": "string",
    "email": "string",
    "url": "string",
    "number": "number",
    "bool": "boolean",
    "date": "string",  # ISO string on the wire
    "autodate": "string",
    "json": "any",
    "relation": "string",  # related record id
    "file": "string",
}


def _ts_type(f: Dict[str, Any]) -> str:
    ftype = f.get("type", "json")
    if ftype == "select":
        values = f.get("values") or []
        if values:
            return " | ".join(json.dumps(v) for v in values)
        return "string"
    if ftype in ("relation", "file") and (f.get("maxSelect") or 1) > 1:
        return "string[]"
    return _TS_TYPES.get(ftype, "any")


def _load_collections(project_path: Path) -> List[Dict[str, Any]]:
    raw = json.loads(
        (Path(project_path) / "config" / "schema.json").read_text(encoding="utf-8")
    )
    cols = raw["collections"] if isinstance(raw, dict) else raw
    # Tolerate the legacy `options` wrapper here too, or a select declared
    # that way silently types as bare `string` instead of its union.
    from app.living_ui.pocketbase_runtime import normalize_legacy_options

    normalize_legacy_options(cols)
    return [c for c in (cols or []) if isinstance(c, dict) and c.get("name")]


def _iface_name(collection: str) -> str:
    # "boardColumns" -> "BoardColumn", "cards" -> "Card"
    name = collection[0].upper() + collection[1:]
    return name[:-1] if name.endswith("s") and len(name) > 2 else name


_TYPES_HEADER = """\
/**
 * GENERATED from config/schema.json — DO NOT EDIT.
 *
 * One interface per declared PocketBase collection, field names exactly
 * as declared (plus PB system fields id/created/updated). Regenerated by
 * the platform on every schema write.
 *
 * Import from here:  import type { Card } from \'../types.gen\'
 * App-specific NON-entity types still go in types.ts.
 */
"""


def render_types(collections: List[Dict[str, Any]]) -> str:
    lines = [_TYPES_HEADER]
    if not collections:
        lines.append(
            "// No collections declared yet — define them in config/schema.json."
        )
        lines.append("export {}")
        return "\n".join(lines) + "\n"
    for col in collections:
        lines.append(f"export interface {_iface_name(col['name'])} {{")
        lines.append("  id: string")
        for f in col.get("fields") or []:
            if not isinstance(f, dict) or not f.get("name"):
                continue
            optional = "" if f.get("required") else " | null"
            lines.append(f"  {f['name']}: {_ts_type(f)}{optional}")
        lines.append("  created: string")
        lines.append("  updated: string")
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


_API_HEADER = """\
/**
 * GENERATED from config/schema.json — DO NOT EDIT. Typed collection helpers.
 *
 * The backend is PocketBase: full CRUD/filter/sort/realtime per collection
 * comes from the PB SDK. Use these typed helpers (or `pb` directly):
 *
 *   import { api, useCards } from \'../api.gen\'
 *   const cards = await api.cards.getFullList({ sort: \'-created\' })
 *   const store = useCards({ filter: \'position > 0\' })   // {items, loading, error}
 *
 * ApiService is ONLY for custom pb_hooks endpoints (/api/custom/...).
 */
"""


def render_api_client(collections: List[Dict[str, Any]]) -> str:
    if not collections:
        return (
            _API_HEADER
            + "\n// No collections declared yet — define them in config/schema.json.\n"
            + "import { pb } from './lib/pb'\n\nexport { pb }\nexport const api = {} as const\n"
        )
    names = [c["name"] for c in collections]
    ifaces = [_iface_name(n) for n in names]
    lines = [_API_HEADER]
    lines.append("import { pb } from './lib/pb'")
    lines.append(
        "import { useEntities as useEntitiesRaw, type ListParams, type EntityStore } "
        "from './services/data'"
    )
    lines.append(
        "import type { " + ", ".join(sorted(set(ifaces))) + " } from './types.gen'"
    )
    lines.append("")
    lines.append("export { pb }")
    lines.append("export type { ListParams, EntityStore }")
    lines.append("")
    # Collection-name → record-type map. It makes the ERGONOMIC call the
    # model naturally writes — `useEntities('cards')` — fully typed as
    # EntityStore<Card> with NO explicit type argument, closing the hole
    # where the untyped raw hook degraded every record to {id:string}.
    lines.append("export interface CollectionRecords {")
    for name, iface in zip(names, ifaces):
        lines.append(f"  {name}: {iface}")
    lines.append("}")
    lines.append("")
    lines.append("/** Typed entity hook: `useEntities('cards')` -> EntityStore<Card>.")
    lines.append(" *  Live realtime list + create/update/remove. Prefer this (or the")
    lines.append(" *  api.<collection> client) over the raw untyped hook. */")
    lines.append("export function useEntities<K extends keyof CollectionRecords>(")
    lines.append("  collection: K,")
    lines.append("  params?: ListParams,")
    lines.append("): EntityStore<CollectionRecords[K]> {")
    lines.append("  return useEntitiesRaw<CollectionRecords[K]>(collection, params)")
    lines.append("}")
    lines.append("")
    lines.append("export const api = {")
    hooks = []
    for name, iface in zip(names, ifaces):
        lines.append(f"  {name}: pb.collection<{iface}>('{name}'),")
        hook = "use" + name[0].upper() + name[1:]
        hooks.append(
            f"export function {hook}(params?: ListParams): EntityStore<{iface}> {{\n"
            f"  return useEntitiesRaw<{iface}>('{name}', params)\n}}"
        )
    lines.append("} as const")
    lines.append("")
    lines.extend(hooks)
    return "\n".join(lines) + "\n"


def regenerate_types(project_path) -> bool:
    """Regenerate types.gen.ts + api.gen.ts. Fail-silent, returns success."""
    try:
        root = Path(project_path)
        collections = _load_collections(root)
        fe = root / "frontend"
        fe.joinpath("types.gen.ts").write_text(
            render_types(collections), encoding="utf-8"
        )
        fe.joinpath("api.gen.ts").write_text(
            render_api_client(collections), encoding="utf-8"
        )
        return True
    except Exception as e:
        logger.debug(f"[LIVING_UI:TYPEGEN] skipped: {e}")
        return False
