#!/usr/bin/env python3
"""Generate a hash-pinned lock file from requirements.txt.

Every install path — pip, conda, and the installer — must install the same
set, and that is only possible if the set is written down. requirements.txt
declares 56 packages; the real closure is 239.

Uses pip's own resolver via `--dry-run --report`, so it needs no lock tool
(uv / pip-tools) in the build environment.

Locks are PER PLATFORM AND PYTHON VERSION and are not interchangeable:
`torch==X` means CPU wheels on Windows and CUDA libraries on Linux, so each
one has to be generated on the platform it describes.

Usage:
    python scripts/generate_lock.py                  # write this platform's lock
    python scripts/generate_lock.py --check          # verify committed locks

## What --check means

That every committed lock was generated from the CURRENT requirements.txt —
compared by the source digest in each lock's header, not by re-resolving.

Re-resolving would be wrong. requirements.txt is unpinned, so a fresh resolve
picks up whatever upstream published since, and the check would report STALE
because `fonttools` shipped a patch release overnight. That makes the check
permanently red and, if CI acted on it, would bump all 239 packages on every
run — the opposite of what a lock is for.

Stale therefore means "someone edited requirements.txt without regenerating",
which is the thing worth catching. Upgrading dependencies is a deliberate act:
run this script without --check.
"""

from __future__ import annotations

import argparse
import glob
import hashlib
import io
import json
import os
import re
import subprocess
import sys
import sysconfig
import tempfile
from typing import Dict, List

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REQUIREMENTS = os.path.join(REPO_ROOT, "requirements.txt")
LOCK_DIR = os.path.join(REPO_ROOT, "requirements")


def lock_tag() -> str:
    """Identify the (platform, python) this lock is valid for.

    sysconfig's platform tag rather than sys.platform: it distinguishes
    macosx arm64 from x86_64, which matters because the wheels differ.
    """
    plat = sysconfig.get_platform().replace(".", "_").replace("-", "_")
    py = f"py{sys.version_info.major}{sys.version_info.minor}"
    return f"{plat}-{py}"


def lock_path() -> str:
    return os.path.join(LOCK_DIR, f"lock-{lock_tag()}.txt")


def resolve() -> List[dict]:
    """Ask pip to resolve requirements.txt without installing anything."""
    fd, report = tempfile.mkstemp(suffix=".json", prefix="craftbot-lock-")
    os.close(fd)
    try:
        proc = subprocess.run(
            [
                sys.executable,
                "-m",
                "pip",
                "install",
                "--dry-run",
                "--ignore-installed",
                "--quiet",
                "--report",
                report,
                "-r",
                REQUIREMENTS,
            ],
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            sys.stderr.write(proc.stdout + proc.stderr)
            raise SystemExit(f"pip resolution failed ({proc.returncode})")
        with io.open(report, encoding="utf-8") as fh:
            return json.load(fh).get("install", [])
    finally:
        try:
            os.unlink(report)
        except OSError:
            pass


def render(entries: List[dict]) -> str:
    """Render a pip --require-hashes compatible lock."""
    rows: Dict[str, List[str]] = {}
    for item in entries:
        meta = item.get("metadata", {})
        name = (meta.get("name") or "").strip()
        version = (meta.get("version") or "").strip()
        if not name or not version:
            continue
        hashes = item.get("download_info", {}).get("archive_info", {}).get("hashes", {})
        sha = hashes.get("sha256")
        key = f"{name}=={version}"
        rows.setdefault(key, [])
        if sha:
            rows[key].append(f"sha256:{sha}")

    unhashed = [k for k, v in rows.items() if not v]
    if unhashed:
        raise SystemExit(
            "Cannot lock — no sha256 for: "
            + ", ".join(sorted(unhashed))
            + "\n--require-hashes needs every entry hashed."
        )

    out = [
        "# GENERATED by scripts/generate_lock.py — do not edit by hand.",
        "# Regenerate with: python scripts/generate_lock.py",
        "#",
        f"# Valid ONLY for: {lock_tag()}",
        "# Locks are per platform+python: torch means CPU wheels on Windows and",
        "# CUDA libraries on Linux, so one lock cannot serve every runner.",
        "#",
        f"# Source: requirements.txt ({_source_digest()})",
        f"# Packages: {len(rows)}",
        "",
        "--require-hashes",
        "",
    ]
    for key in sorted(rows, key=str.lower):
        joined = " \\\n    ".join(f"--hash={h}" for h in sorted(rows[key]))
        out.append(f"{key} \\\n    {joined}")
    return "\n".join(out) + "\n"


def _source_digest() -> str:
    with io.open(REQUIREMENTS, encoding="utf-8") as fh:
        body = "".join(
            line.strip()
            for line in fh
            if line.strip() and not line.strip().startswith("#")
        )
    return "sha256:" + hashlib.sha256(body.encode()).hexdigest()[:16]


def _check_committed_locks() -> int:
    """Verify every committed lock came from the current requirements.txt.

    Checks all of them, not just this platform's: a Windows machine should
    still be told that the Linux lock is out of date, because someone has to
    regenerate it somewhere. Needs no pip resolve, so it is instant.
    """
    digest = _source_digest()
    locks = sorted(glob.glob(os.path.join(LOCK_DIR, "lock-*.txt")))
    if not locks:
        print("MISSING: no lock files at all — run this script without --check")
        return 1

    stale = []
    for path in locks:
        name = os.path.relpath(path, REPO_ROOT)
        with io.open(path, encoding="utf-8") as fh:
            header = fh.read(2048)
        match = re.search(r"^# Source: requirements\.txt \((sha256:[0-9a-f]+)\)", header, re.M)
        if match is None:
            print(f"UNREADABLE: {name} has no source digest — regenerate it")
            stale.append(name)
        elif match.group(1) != digest:
            print(f"STALE: {name} was generated from a different requirements.txt")
            stale.append(name)
        else:
            print(f"OK: {name}")

    if stale:
        print()
        print("requirements.txt changed without regenerating these locks.")
        print("Run `python scripts/generate_lock.py` on each affected platform.")
        return 1
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify every committed lock matches requirements.txt (for CI)",
    )
    args = ap.parse_args()

    if args.check:
        return _check_committed_locks()

    target = lock_path()
    rendered = render(resolve())

    os.makedirs(LOCK_DIR, exist_ok=True)
    with io.open(target, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(rendered)
    print(f"wrote {os.path.relpath(target, REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
