# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for CraftBotInstaller.exe — the small wizard/installer.

Bundles ONLY: craftbot.py, the installer/ package (api/helpers/metadata/
payload/wizard + the ui/ window), CustomTkinter and its theme assets, a
stdlib-only slice of app/ for runtime provisioning, the icon files, and a
VERSION file. No agent code, no openai/anthropic/chromadb — those come from
CraftBot-src.zip, which this installer downloads from GitHub Releases at
install time.

The wizard is a real application window drawn with CustomTkinter on top of
Tk (installer/ui/). Tk ships with CPython and is bundled here, so the
installer depends on nothing being present on the user's machine — which is
the whole point, and is what the two previous UIs got wrong. See
installer/wizard.py for that history.

Result: a ~17 MB onefile EXE. Double-click opens the window; CLI subcommands
(install / start / stop / status / uninstall / repair) work without one.

Build from the repo root: `python -m PyInstaller packaging/CraftBotInstaller.spec`.
All paths below are derived from SPECPATH (the absolute directory of this
spec file), so the build works regardless of the current working directory.
"""

import os as _os

from PyInstaller.utils.hooks import collect_data_files

# SPECPATH is set by PyInstaller to the directory containing this spec file
# (i.e. <repo>/packaging/). ROOT walks one level up to the project root so
# we can reference craftbot.py, installer/, assets/, rthooks/ etc. via
# absolute paths.
ROOT = _os.path.dirname(SPECPATH)

# CustomTkinter loads its themes from JSON and its widget assets from disk
# at import time, so the package's data files have to ship or the window
# raises FileNotFoundError the moment it is constructed. PyInstaller's module
# graph does not see files opened by path, only imports, which is exactly the
# class of omission that shipped a broken build as issue #439.
datas = collect_data_files('customtkinter')

datas += [
    # The installer/ package — wizard + ui/ + helpers + metadata + payload.
    # This also carries installer/ui/assets/, the window's pre-rendered logo
    # frames. They are opened by path, which PyInstaller's module graph cannot
    # see, so shipping the package wholesale is what keeps them present.
    # Top-level imports in craftbot.py mean PyInstaller's analyser already
    # bundles these as bytecode, but we keep the source files alongside so
    # tracebacks and debugging show real lines instead of <frozen ...>.
    (_os.path.join(ROOT, 'installer'), 'installer'),
    (_os.path.join(ROOT, 'craftbot_logo_1.ico'), '.'),
    (_os.path.join(ROOT, 'craftbot_logo_1.png'), '.'),
]

# VERSION file is generated by the release workflow (echo of the git tag)
# at the project root. Bundle it if present so
# craftbot._read_bundled_version() pins the installer to the matching agent
# version.
_version_path = _os.path.join(ROOT, 'VERSION')
if _os.path.isfile(_version_path):
    datas.append((_version_path, '.'))


a = Analysis(
    [_os.path.join(ROOT, 'craftbot.py')],
    pathex=[ROOT],  # so `import craftbot` and `from installer import ...` resolve
    binaries=[],
    datas=datas,
    # The wizard now provisions the Node and Python runtimes itself (see
    # craftbot._full_install_frozen). Those stages live in app.provision, so
    # a bounded slice of app/ must ship: app/__init__.py is empty and every
    # module here is stdlib-only, so this pulls in no third-party weight.
    # This is why 'app' is no longer a blanket exclude below.
    hiddenimports=[
        # The window and its modules are imported inside launch_wizard() so a
        # CLI-only run never touches Tk. Listing them keeps them bundled
        # regardless of how PyInstaller treats deferred imports.
        'installer.wizard',
        'installer.ui',
        'installer.ui.window',
        'installer.ui.glass',
        'installer.ui.theme',
        'installer.ui.chrome',
        'customtkinter',
        'darkdetect',
        'app.paths',
        'app.python_runtime',
        'app.node_runtime',
        'app.provision',
        'app.provision.types',
        'app.provision.pipeline',
        'app.provision.runtimes',
        'app.provision.deps',
        'app.provision.verify',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[
        # Same hooks the agent uses. The installer is also console=False so
        # any subprocess it spawns (powershell for shortcut, schtasks for
        # auto-start, taskkill for stop) would otherwise flash a console.
        _os.path.join(ROOT, 'rthooks', 'rthook-utf8-stdio.py'),
        _os.path.join(ROOT, 'rthooks', 'rthook-windows-noflash.py'),
    ],
    excludes=[
        # Be aggressive — none of this belongs in the installer EXE.
        'torch', 'torchvision', 'torchaudio', 'triton', 'nvidia',
        'transformers', 'cv2', 'matplotlib', 'tensorflow',
        'openai', 'anthropic', 'chromadb', 'tiktoken', 'tiktoken_ext',
        'fastapi', 'starlette', 'uvicorn', 'pydantic',
        'numpy', 'scipy', 'pandas', 'sklearn',
        # The agent's own modules — the installer never imports them.
        # 'app' is deliberately NOT excluded: craftbot.py imports app.paths,
        # app.node_runtime and app.provision to provision the runtimes. All
        # are stdlib-only, and nothing else under app/ is statically
        # reachable from craftbot.py, so this does not drag the agent in.
        'agent_core', 'agents', 'decorators', 'skills',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CraftBotInstaller',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # No terminal flash on double-click; wizard owns the UX
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=_os.path.join(ROOT, 'craftbot_logo_1.ico'),
)
