"""
Living UI System Routes (SYSTEM-MANAGED — do not edit)

The agent observation/state API every Living UI ships with:

    GET/PUT/DELETE /api/state      generic JSON state (merge on PUT)
    POST /api/state/replace        replace state wholesale
    POST /api/action               named actions (reset/increment/...)
    GET/POST /api/ui-snapshot      UI state observation
    GET/POST /api/ui-screenshot    UI visual observation

App data endpoints do NOT live here — they are generated by the engine
from config/schema.json, and custom endpoints go in routes.py.
"""

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import Dict, Any, List, Optional
from database import get_db
from system_models import AppState, UISnapshot, UIScreenshot
from datetime import datetime
import logging

logger = logging.getLogger(__name__)
router = APIRouter()


# ============================================================================
# Pydantic Schemas
# ============================================================================


class StateUpdate(BaseModel):
    """Schema for updating app state."""

    data: Dict[str, Any]


class ActionRequest(BaseModel):
    """Schema for executing an action."""

    action: str
    payload: Optional[Dict[str, Any]] = None


class UISnapshotUpdate(BaseModel):
    """Schema for updating UI snapshot."""

    htmlStructure: Optional[str] = None
    visibleText: Optional[List[str]] = None
    inputValues: Optional[Dict[str, Any]] = None
    componentState: Optional[Dict[str, Any]] = None
    currentView: Optional[str] = None
    viewport: Optional[Dict[str, Any]] = None


class UIScreenshotUpdate(BaseModel):
    """Schema for updating UI screenshot."""

    imageData: str  # Base64 encoded PNG
    width: Optional[int] = None
    height: Optional[int] = None


# ============================================================================
# State Management Routes
# ============================================================================


@router.get("/state")
def get_state(db: Session = Depends(get_db)) -> Dict[str, Any]:
    """Get the current application state (empty dict if none exists)."""
    state = db.query(AppState).first()
    if not state:
        state = AppState(data={})
        db.add(state)
        db.commit()
        db.refresh(state)
    return state.data or {}


@router.put("/state")
def update_state(update: StateUpdate, db: Session = Depends(get_db)) -> Dict[str, Any]:
    """Merge the provided data into the application state."""
    state = db.query(AppState).first()
    if not state:
        state = AppState(data=update.data)
        db.add(state)
    else:
        state.update_data(update.data)
    db.commit()
    db.refresh(state)
    logger.info(f"[SystemRoutes] State updated: {list(update.data.keys())}")
    return state.data or {}


@router.post("/state/replace")
def replace_state(update: StateUpdate, db: Session = Depends(get_db)) -> Dict[str, Any]:
    """Replace the entire application state (PUT /state merges instead)."""
    state = db.query(AppState).first()
    if not state:
        state = AppState(data=update.data)
        db.add(state)
    else:
        state.data = update.data
    db.commit()
    db.refresh(state)
    logger.info("[SystemRoutes] State replaced")
    return state.data or {}


@router.delete("/state")
def clear_state(db: Session = Depends(get_db)) -> Dict[str, str]:
    """Clear all application state (resets to empty dict)."""
    state = db.query(AppState).first()
    if state:
        state.data = {}
        db.commit()
    logger.info("[SystemRoutes] State cleared")
    return {"status": "cleared"}


@router.post("/action")
def execute_action(
    request: ActionRequest, db: Session = Depends(get_db)
) -> Dict[str, Any]:
    """
    Execute a named action against the generic state.

    Built-ins: reset, increment, decrement. App-specific verbs belong in
    routes.py as real endpoints (declared in config/operations.json).
    """
    action = request.action
    payload = request.payload or {}

    logger.info(f"[SystemRoutes] Executing action: {action}")

    state = db.query(AppState).first()
    if not state:
        state = AppState(data={})
        db.add(state)

    current_data = state.data or {}

    if action == "reset":
        state.data = {}
        db.commit()
        return {"status": "reset", "data": {}}

    elif action == "increment":
        key = payload.get("key", "counter")
        current_data[key] = current_data.get(key, 0) + 1
        state.data = current_data
        db.commit()
        return {"status": "incremented", "data": current_data}

    elif action == "decrement":
        key = payload.get("key", "counter")
        current_data[key] = current_data.get(key, 0) - 1
        state.data = current_data
        db.commit()
        return {"status": "decremented", "data": current_data}

    else:
        logger.warning(f"[SystemRoutes] Unknown action: {action}")
        return {"status": "unknown_action", "action": action, "data": current_data}


# ============================================================================
# UI Observation Routes (Agent API)
# ============================================================================


@router.get("/ui-snapshot")
def get_ui_snapshot(db: Session = Depends(get_db)) -> Dict[str, Any]:
    """Get the latest UI snapshot captured by the frontend."""
    snapshot = db.query(UISnapshot).first()
    if not snapshot:
        return {
            "htmlStructure": None,
            "visibleText": [],
            "inputValues": {},
            "componentState": {},
            "currentView": None,
            "viewport": {},
            "timestamp": None,
            "status": "no_snapshot",
        }
    return snapshot.to_dict()


@router.post("/ui-snapshot")
def update_ui_snapshot(
    data: UISnapshotUpdate, db: Session = Depends(get_db)
) -> Dict[str, Any]:
    """Frontend posts UI state here periodically (replaces WebSocket)."""
    snapshot = db.query(UISnapshot).first()
    if not snapshot:
        snapshot = UISnapshot()
        db.add(snapshot)

    if data.htmlStructure is not None:
        snapshot.html_structure = data.htmlStructure
    if data.visibleText is not None:
        snapshot.visible_text = data.visibleText
    if data.inputValues is not None:
        snapshot.input_values = data.inputValues
    if data.componentState is not None:
        snapshot.component_state = data.componentState
    if data.currentView is not None:
        snapshot.current_view = data.currentView
    if data.viewport is not None:
        snapshot.viewport = data.viewport

    snapshot.timestamp = datetime.utcnow()

    db.commit()
    db.refresh(snapshot)
    logger.info("[SystemRoutes] UI snapshot updated")
    return snapshot.to_dict()


@router.get("/ui-screenshot")
def get_ui_screenshot(db: Session = Depends(get_db)) -> Dict[str, Any]:
    """Get the latest UI screenshot (base64 PNG) posted by the frontend."""
    screenshot = db.query(UIScreenshot).first()
    if not screenshot or not screenshot.image_data:
        return {
            "imageData": None,
            "width": None,
            "height": None,
            "timestamp": None,
            "status": "no_screenshot",
        }
    return screenshot.to_dict()


@router.post("/ui-screenshot")
def update_ui_screenshot(
    data: UIScreenshotUpdate, db: Session = Depends(get_db)
) -> Dict[str, Any]:
    """Frontend posts a base64 PNG screenshot of the current UI."""
    screenshot = db.query(UIScreenshot).first()
    if not screenshot:
        screenshot = UIScreenshot()
        db.add(screenshot)

    screenshot.image_data = data.imageData
    screenshot.width = data.width
    screenshot.height = data.height
    screenshot.timestamp = datetime.utcnow()

    db.commit()
    db.refresh(screenshot)
    logger.info(
        f"[SystemRoutes] UI screenshot updated ({data.width}x{data.height})"
    )
    return {"status": "updated", "timestamp": screenshot.timestamp.isoformat()}
